Cargo.lock, Cargo.toml, src/common/error.rs, src/tests/common/traits/mod.rs, src/tests/mod.rs, src/tests/tpm/android/mod.rs, src/tpm/android/utils.rs, src/tpm/mod.rs
After merging the last PR some use-flags and settings in cargo.toml had to be adjusted.
=> bugfix/Fixed minor use-flag errors after merge

src/common/config.rs, src/common/crypto/algorithms/encryption.rs, src/common/crypto/algorithms/hashes.rs, src/common/crypto/algorithms/mod.rs, src/common/factory.rs, src/common/mod.rs, src/common/traits/key_handle.rs, src/common/traits/module_provider.rs, src/stub/mod.rs, src/tests/mod.rs
Fixes import errors with the default features.
=> fix: feature gated flutter_bridge import with flutter feature

src/common/crypto/algorithms/hashes.rs, src/tests/tpm/apple_secure_enclave/execute_test.ps1, src/tests/tpm/apple_secure_enclave/mod.rs, src/tpm/apple_secure_enclave/key_handle.rs, src/tpm/apple_secure_enclave/mod.rs, src/tpm/apple_secure_enclave/provider.rs
Added better parsing of supported key algorithms.
Fixed and issue with the test script.
=> feat(apple secure enclave): multiple hash algorithms

Cargo.toml, binary-knights.entitlement, flutter_app/ios/Flutter/Debug.xcconfig, flutter_app/ios/Flutter/Release.xcconfig, flutter_app/ios/Podfile, flutter_app/lib/crypto.dart, flutter_app/lib/signing_page.dart, flutter_app/macos/Flutter/Flutter-Debug.xcconfig, flutter_app/macos/Flutter/Flutter-Release.xcconfig, flutter_app/macos/Podfile, flutter_app/macos/Podfile.lock, flutter_app/macos/Runner.xcodeproj/project.pbxproj, flutter_app/macos/Runner.xcworkspace/contents.xcworkspacedata, flutter_app/macos/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings, flutter_plugin/rust/Cargo.lock, flutter_plugin/rust/Cargo.toml, src/common/config.rs, src/common/factory.rs, src/tests/mod.rs, src/tests/tpm/apple_secure_enclave/execute_test.ps1, src/tpm/apple_secure_enclave/key_handle.rs, src/tpm/apple_secure_enclave/provider.rs
* Added logging to the apple secure enclave provider.
* Added logging initialization to the integration tests.
* Switched to messagepack for writing the metadata.
=> Fix(Apple Secure Enclave): Metadata Never Deleted, Failing Compilation

Cargo.lock, Cargo.toml, src/common/config.rs, src/common/error.rs, src/storage/mod.rs, src/tpm/apple_secure_enclave/provider.rs
This PR implements a db backend for storing key metadata as file.
=> Feature(Storage Manager): File Storage

src/tests/software/provider_tests.rs
- fix: adjusted derive_key tests & test setup
=> fix: split the derive_key tests & derive_key bugfixing

src/tests/software/provider_tests.rs
- fix: bug in test after merge
=> fix: fix test after merge

Taskfile.yml, cSpell.json, ts-types/package.json
- **ci: added taskfile**
- **ci: fixed test execution**
- **ci: fix generate task**
- **ci: added alias for running flutter app**
-   [ ] Do the dart bindings have to be …
=> CI: Add Taskfile

Taskfile.yml
- **fix: dart binding generation**
- **ci: taskfile added alias**
=> CI: Fix Taskfile Dart Binding Generation

flutter_plugin/lib/src/rust/frb_generated.dart, flutter_plugin/lib/src/rust/third_party/crypto_layer/common.dart, flutter_plugin/rust/src/frb_generated.rs, src/tpm/android/utils.rs
- **fix(flutter plugin): missing dart bindings for prior non exposed method hash**
- **fix(android): not compiling due addition of blak2 in crypto hash**
=> Fix: Android Provider not Compiling

cSpell.json, src/software/provider.rs, src/tests/software/provider_tests.rs
* Added many error logs.
*  Removed except statements in favor of returning errors.
-   [ ] Do the dart bindings have to be [re-generated](https://github.com/nmshd/rust-crypto/tree/main/flutter_plugin#generating-dart-binding …
=> Test(software provider): Added More Logging, Removed Exception in Favor Of Errors

src/software/provider.rs
=> fix: bug in generate_session_keys

Cargo.lock, Cargo.toml, src/software/provider.rs, src/tests/software/provider_tests.rs
=> fix: replaced ECDH ring implementation

src/software/provider.rs
=> fix: added debug statements to DH Exchange

src/common/mod.rs, src/common/traits/key_handle.rs, src/software/provider.rs, src/stub/mod.rs, src/tests/software/provider_tests.rs
=> fix: fixed dh exchange for node plugin

src/software/key_handle.rs
=> fix: adjust error handling for encryption

src/software/key_handle.rs, src/tests/software/key_handle_tests.rs
=> fix: fixed encryption/decryption with xchacha20 & iv usage

.github/workflows/unit-test-pr.yml
* Run ts-types checks and rust unit-tests in parallel.
﻿
=> CI: Run Tests in Parallel

flutter_plugin/lib/src/rust/frb_generated.dart, flutter_plugin/lib/src/rust/third_party/crypto_layer/common.dart, flutter_plugin/rust/src/frb_generated.rs, src/common/mod.rs, src/common/traits/key_handle.rs, src/software/key_handle.rs, src/storage/mod.rs, src/stub/mod.rs, src/tests/software/key_handle_tests.rs, src/tests/software/provider_tests.rs, src/tpm/android/key_handle.rs, src/tpm/apple_secure_enclave/key_handle.rs, ts-types/manual/KeyHandle.ts, ts-types/manual/KeyPairHandle.ts, ts-types/package.json
- Encrypt method needs IV parameter
-   [X] Do the unit tests in CAL run? Check at least those that you can run: `cargo test -F software`
-   [X] Are changes in common propagated to all providers that are currently in use?
-   [X] `software`
-   [X] `tpm/android`
-   [X] `tpm/apple_secure_enclave`
-   [X] Did changes in the API occur, such that `./ts-types` needs to be updated?
-   [-] [Generate types partially](https://github.com/nmshd/rust-crypto/tree/main/ts-types#generate-the-types).
-   [X] Have you given the maintainer of [`crypto-layer-node`](https://github.com/nmshd/crypto-layer-node) a heads up?
-   [ ] Does the flutter plugin still …
=> Fix: added IV parameter to encrypt

src/common/mod.rs, src/common/traits/key_handle.rs, src/software/key_handle.rs, src/stub/mod.rs, src/tpm/android/key_handle.rs
=> feature: add scaffolding for KeyHandle::derive_key

Taskfile.yml, flutter_app/integration_test/cal_test.dart, src/software/key_handle.rs, src/tpm/android/key_handle.rs, src/tpm/android/provider.rs, src/tpm/android/wrapper/key_generation/key_protection.rs, src/tpm/android/wrapper/key_generation/mod.rs, src/tpm/android/wrapper/key_generation/protections_builder.rs, src/tpm/android/wrapper/key_store/key_entry.rs
=> feat(android): add key derivation for Android

cal_flutter_plugin/lib/src/rust/api/crypto.dart, cal_flutter_plugin/lib/src/rust/frb_generated.dart, cal_flutter_plugin/rust/src/api/crypto.rs, cal_flutter_plugin/rust/src/frb_generated.rs
=> feat(cal_flutter_plugin): add createWithKvConfig function

cal_flutter_plugin/rust/src/lib.rs, flutter_app/android/app/src/main/kotlin/com/example/cal_flutter_app/MainActivity.kt, src/provider/software/provider.rs
=> fix(android): fix android JNI_onLoad()

src/storage/storage_backend/file_store.rs
=> fix(StorageManager): flush db

Cargo.lock, Cargo.toml, src/provider/android/wrapper/context.rs
=> fix: android strongbox check

src/provider/android/wrapper/context.rs
=> fix: syntax error
