nmshd/rust-crypto

.gitignore, src/tests/tpm/win/provider_handle_tests.rs, src/tpm/win/key_handle.rs, src/tpm/win/mod.rs, src/tpm/win/provider.rs
This PR mainly focuses on getting the test `crate::tests::tpm::win::test_create_rsa_key` to work.
=> Fix Errors when Creating RSA Key with Windows TPM Provider

src/common/config.rs, src/common/factory.rs, src/common/traits/module_provider.rs, src/stub/mod.rs
This PR tries to streamline the use of `create_provider`:
* `create_provider` takes a Vec instead of a HashMap.
* Added a `name` function for `ProviderImplConfig` enum.
=> refactor(common)!: create provider

src/common/factory.rs, src/lib.rs
* Lints for rust edition 2024 compatibility. 
* Lints for correctness and other matters.
* Fixed error in doctest.
=> Test(clippy): Added Lints for Edition 2024 Compability and Other Common Problems

node-plugin/crates/crypto-layer-node/src/dhexchange.rs, node-plugin/crates/crypto-layer-node/src/fromjs/mod.rs, node-plugin/crates/crypto-layer-node/src/keyhandle.rs, node-plugin/crates/crypto-layer-node/src/keypairhandle.rs, node-plugin/crates/crypto-layer-node/src/provider.rs, node-plugin/crates/crypto-layer-node/src/tojs/mod.rs, node-plugin/tests/key-handle.test.ts, node-plugin/tests/provider.test.ts
* Panic on empty `Uint8Array`.
* Panic on empty slice `&[u8]`.
=> Fix(node plugin): Panic on Empty Typed Array or Empty Slice

flutter_plugin/rust/src/frb_generated.rs
Missing imports in generated code.
=> fix(flutter-plugin): added missing imports in generated bindings

node-plugin/crates/crypto-layer-node/src/lib.rs, node-plugin/crates/crypto-layer-node/src/tojs/mod.rs, node-plugin/src/index.cts, node-plugin/tests/factory.test.ts, src/common/factory.rs, src/prelude.rs
Added to prelude as well.
* Added `getProviderCapabilites` function in the node plugin.
* Added function to rust prelude.
=> fix(node-plugin): added get provider capabilites function

Cargo.lock, Cargo.toml, flutter_plugin/rust/Cargo.lock, flutter_plugin/rust/src/lib.rs, src/common/error.rs, src/common/factory.rs, src/common/mod.rs, src/common/traits/module_provider.rs, src/software/mod.rs, src/stub/mod.rs, src/tpm/android/error.rs, src/tpm/android/key_handle.rs, src/tpm/android/provider.rs, src/tpm/android/wrapper/context.rs, src/tpm/apple_secure_enclave/provider.rs, ts-types/index.ts
Allow android provider to check if Android context was initialized and return None for `get_name` and `get_capabilities`.
`get_name` return `Option<String>` instead of `String`.
=> feature(android): allow android provider to check context

.vscode/settings.json, flutter_app/README.md, flutter_plugin/README.md, ts-types/README.md
* Fixed headings of `README` not rendering correctly.
* Might have some MD lint ongoing.
=> Docs: Fix README Headers

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/release.yml, ts-types/README.md, ts-types/package.json
=> ci(ts-types): added release gh workflow

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/release.yml, flutter_app/README.md, flutter_plugin/README.md, ts-types/README.md
* Fixed wrong working dir for release gh workflow.
=> fix(ci): wrong working dir for npm execution

.github/workflows/release.yml
* Fixed permissions for gh workflow release of ts types.
-   [ ] Does the …
=> ci(release): fix permissions

ts-types/manual/DHExchange.ts, ts-types/manual/Provider.ts, ts-types/package.json
* Fixed wrong import of generated types instead of manual types.
-   [ ] Does …
=> Fix(ts types): Wrong Import

ts-types/README.md
* Added badge with version to readme of ts types.
-   [ ] Does the flutter …
=> docs(ts types): added badge to readme with link to npmjs site

flutter_plugin/lib/src/rust/frb_generated.dart, flutter_plugin/lib/src/rust/third_party/crypto_layer/common.dart, flutter_plugin/lib/src/rust/third_party/crypto_layer/common/factory.dart, flutter_plugin/rust/src/frb_generated.rs, src/common/mod.rs, ts-types/manual/Provider.ts, ts-types/package.json
* Exposes `derive_key_from_password` and `get_random` methods of `Provider` in cal and in ts types.
* Version bump of ts types.
-   [x] Did changes in the API occur, such that `./ts-types` needs to be updated?
-   [x] Do the dart bindings have to be …
=> Feature: Expose Derive Key and Get Random Methods

src/software/mod.rs, src/software/provider.rs, src/tests/software/provider_tests.rs
Added keyspec usage to key exchange
-   [X] Do the unit tests in CAL run? Check at least those that you can run: `cargo test -F software`
-   [X] `software`
=> fix: added keyspec usage in key exchange

Cargo.lock, Cargo.toml, Taskfile.yml, cSpell.json, flutter_plugin/lib/src/rust/third_party/crypto_layer/common/crypto/algorithms/hashes.dart, flutter_plugin/rust/Cargo.lock, flutter_plugin/rust/src/frb_generated.rs, src/common/crypto/algorithms/hashes.rs, src/common/traits/module_provider.rs, src/software/provider.rs, ts-types/generated/CryptoHash.ts, ts-types/manual/Provider.ts, ts-types/package.json
- Hash method for provider trait
- Hash implementation for software provider
-   [X] Do the unit tests in CAL run? Check at least those that you can run: `cargo test -F software`
-   [X] `software`
-   [X] Did changes in the API occur, such that `./ts-types` needs to be updated?
-   [x] [Generate types partially](https://github.com/nmshd/rust-crypto/tree/main/ts-types#generate-the-types).
-   [x] Have you given the maintainer of [`crypto-layer-node`](https://github.com/nmshd/crypto-layer-node) a heads up?
-   [x] Do the dart bindings have to be [re-generated](https://github.com/nmshd/rust-crypto/tree/main/flutter_plugin#generating-dart-bindings)?
- …
=> feature: added hash method

src/common/mod.rs, src/tests/software/provider_tests.rs
* Fixed hash method of provider not being exposed.
-   [ ] Does the flutter …
=> Fix: Hash Method not Exposed

.github/workflows/release.yml, Taskfile.yml, cSpell.json, ts-types/.vscode/settings.json, ts-types/checks/index.ts, ts-types/package-lock.json, ts-types/package.json, ts-types/tsconfig.json
* Added functions for asserting that objects are of type.
* CI installs npm dependencies locked.
-   [ ] Do the dart bindings have to be [re-generated](https://github.com/nmshd/rust-crypto/tree/main/flutter_plugin#generating …
=> Test(ts types): New Assert and Is Functions For Testing

ts-types/.npmignore, ts-types/package.json
* Fixed missing dist folder in release v0.5.* on npmjs.
-   [ ] Does the …
=> Fix(ts types): Missing Dist Folder

flutter_plugin/lib/src/rust/frb_generated.dart, flutter_plugin/lib/src/rust/third_party/crypto_layer/common.dart, flutter_plugin/rust/src/frb_generated.rs, src/common/mod.rs, src/common/traits/key_handle.rs, src/software/provider.rs, src/stub/mod.rs
DHKeyExchange::id()
KeyPairHandle::start_dh_exchange()
-   [ ] Does the flutter …
=> fix: add missing id function to DHExchange, add missing start_dh_exchange function

flutter_plugin/lib/src/rust/frb_generated.dart, flutter_plugin/lib/src/rust/frb_generated.io.dart, flutter_plugin/lib/src/rust/frb_generated.web.dart, flutter_plugin/lib/src/rust/third_party/crypto_layer/common.dart, flutter_plugin/lib/src/rust/third_party/crypto_layer/common/crypto/algorithms/key_derivation.dart, flutter_plugin/lib/src/rust/third_party/crypto_layer/common/crypto/algorithms/key_derivation.freezed.dart, flutter_plugin/rust/src/frb_generated.rs, src/common/crypto/algorithms/key_derivation.rs
=> fix: add non_opaque modifier to Kdf for code generation

flutter_plugin/lib/cal_flutter_plugin.dart
=> fix: export kdf in generated dart code

src/common/mod.rs, src/software/provider.rs, src/tests/software/provider_tests.rs
=> fix: fixed bug in generate_session_keys of SoftwareDHExchange

flutter_plugin/lib/src/rust/frb_generated.dart, flutter_plugin/lib/src/rust/third_party/crypto_layer/common/crypto/algorithms/key_derivation.dart, flutter_plugin/lib/src/rust/third_party/crypto_layer/common/crypto/algorithms/key_derivation.freezed.dart, flutter_plugin/rust/src/frb_generated.rs, src/common/crypto/algorithms/key_derivation.rs, src/software/provider.rs, ts-types/generated/KDF.ts
=> fix: add missing KDF::argon2i option

src/common/mod.rs
* Missing deprecation of `dh_exchange_from_keys`.
-   [ ] Does the flutter …
=> Fix: Missing Deprecation for dh_exchange_from_keys

.github/workflows/unit-test-pr.yml, src/common/mod.rs, src/common/traits/key_handle.rs, src/common/traits/module_provider.rs, ts-types/manual/KeyPairHandle.ts, ts-types/manual/Provider.ts, ts-types/package.json
* Fixed deprecation message in `dh_exchaneg_from_keys` not being shown.
* Marked `start_dh_exchange` in `KeyPairHandle` as deprecated.
* Minor speed improvement for ci.
-   [ ] Do the dart bindings have to be …
=> Changed: Added Deprecations to all non ephemeral DH Exchange Methods

flutter_plugin/lib/src/rust/frb_generated.dart, flutter_plugin/lib/src/rust/frb_generated.io.dart, flutter_plugin/lib/src/rust/frb_generated.web.dart, flutter_plugin/rust/src/frb_generated.rs, src/common/mod.rs
* Deprecated functions where accidentally not set public in #134
-   [x] Do the dart bindings have to be [re-generated](https://github.com/nmshd/rust-crypto/tree/main/flutter_plugin#generating-dart-bindings)?
-   [x] Does …
=> Fix: Unintended API Change

src/software/mod.rs
SoftwareProvider::get_capabilities() should indicate XChaCha and not ChaCha support.
-   [ ] Do the dart bindings have to be [re-generated](https://github.com/nmshd/rust-crypto/tree/main/flutter_plugin#generating-dart-bindin …
=> fix(SoftwareProvider): get_capabilities XChaCha and not ChaCha

.github/workflows/unit-test-pr.yml, flutter_plugin/lib/src/rust/frb_generated.dart, flutter_plugin/lib/src/rust/third_party/crypto_layer/common.dart, flutter_plugin/rust/src/frb_generated.rs, src/common/mod.rs, src/common/traits/key_handle.rs, src/software/key_handle.rs, src/stub/mod.rs, src/tpm/android/key_handle.rs, ts-types/manual/KeyHandle.ts, ts-types/manual/Provider.ts, ts-types/package-lock.json, ts-types/package.json
- **ci: add android provider unit tests on pr**
- **removed: added deprecation notice to derive_key_from_base**
- **refactor!: derive key now takes a slice u8 instead of a string**
- **chore(ts types): bump v0.8.0**
* TS Types API
* Derive key takes slice u8.
* Deprecated derive key from base.
* Android provider tests are also run on pr.
-   [x] Are changes in common propagated to all providers that are currently in use?
-   [x] `software`
-   [x] `tpm/android`
-   [x] Did changes in the API occur, such that `./ts-types` needs to be updated?
-   [x] [Generate types partially](https://github.com/nmshd/rust-crypto/tree/main/ts-types#generate-the-types).
- …
=> Changes for new derive key method

Cargo.lock, Cargo.toml, cSpell.json, flutter_plugin/lib/src/rust/frb_generated.dart, flutter_plugin/lib/src/rust/third_party/crypto_layer/common.dart, flutter_plugin/lib/src/rust/third_party/crypto_layer/common/config.dart, flutter_plugin/lib/src/rust/third_party/crypto_layer/common/crypto/algorithms/encryption.dart, flutter_plugin/lib/src/rust/third_party/crypto_layer/common/crypto/algorithms/hashes.dart, flutter_plugin/rust/Cargo.lock, flutter_plugin/rust/src/frb_generated.rs, src/common/config.rs, src/common/crypto/algorithms/encryption.rs, src/common/crypto/algorithms/hashes.rs, src/common/error.rs, src/common/mod.rs, src/common/traits/key_handle.rs, src/software/key_handle.rs, src/software/provider.rs, src/storage/mod.rs, src/tests/software/key_handle_tests.rs, src/tests/software/provider_tests.rs, ts-types/manual/KeyHandle.ts, ts-types/package-lock.json, ts-types/package.json
* Methods `encrypt` and `encrypt_with_iv` to replace `encrypt_data`.
`encrypt_data` had the implicit behaviour of creating a new iv, if an empty iv was inputed.
This was not documented.
* Creating erros does not involve manually converting descriptions into String.
* Deprecated `encrypt_data` of `KeyHandle`.
-   [x] Are changes in common propagated to all providers that are currently in use?
-   [x] Did changes in the API occur, such that `./ts-types` needs to be updated?
-   [ ] Have you given the …
=> Refactor: Explicit Encryption With or Without IV Methods, Generics for Error Generation

Cargo.lock, Cargo.toml, flutter_plugin/rust/Cargo.lock, src/common/crypto/algorithms/encryption.rs, src/software/key_handle.rs, src/tests/software/key_handle_tests.rs
=> fix(SoftwareProvider): switch XChaCha20 to XChaCha20Poly1305

.github/workflows/unit-test-pr.yml, Taskfile.yml, cal_flutter_plugin/example/pubspec.lock, cal_flutter_plugin/lib/src/rust/frb_generated.dart, cal_flutter_plugin/lib/src/rust/third_party/crypto_layer/common.dart, cal_flutter_plugin/lib/src/rust/third_party/crypto_layer/common/config.dart, cal_flutter_plugin/lib/src/rust/third_party/crypto_layer/common/error.dart, cal_flutter_plugin/lib/src/rust/third_party/crypto_layer/common/error.freezed.dart, cal_flutter_plugin/rust/src/frb_generated.rs, flutter_app/.vscode/settings.json, flutter_app/lib/encryption_page.dart, src/common/config.rs, src/common/error.rs, src/common/mod.rs, src/common/traits/key_handle.rs, src/software/key_handle.rs, src/software/provider.rs, src/stub/mod.rs, src/tests/software/key_handle_tests.rs, src/tests/software/provider_tests.rs, src/tests/tpm/apple_secure_enclave/mod.rs, src/tpm/android/key_handle.rs, src/tpm/apple_secure_enclave/key_handle.rs, ts-types/generated/CalErrorKind.ts, ts-types/generated/KeySpec.ts, ts-types/manual/KeyPairHandle.ts, ts-types/package-lock.json, ts-types/package.json
* `non_exportable` flag for `KeySpec`.
* Dart code gen not generating bindings correctly, when api changed.
* Removed `iv` argument of `encrypt_data` of `KeyPairHandle`.
* ts types version bump.
-   [x] Are changes in common propagated to all providers that are currently in use?
-   [x] `software`
-   [x] `tpm/android`
-   [x] `tpm/apple_secure_enclave`
-   [x] Did changes in the API occur, such that `./ts-types` needs to be updated?
-   [x] [Generate types partially](https://github.com/nmshd/rust-crypto/tree/main/ts-types#generate-the-types).
-   [x] Do the dart bindings …
=> Feature: Non Exportable for KeySpec, Fix Wrong Iv For KeyPairHandle

cal_flutter_plugin/lib/src/rust/third_party/crypto_layer/common/factory.dart, cal_flutter_plugin/rust/src/api/crypto.rs
fix missing use statement in flutter_plugin
-   [ ] Does the flutter plugin …
=> fix(flutter_plugin): missing import after `task generate`

src/provider/android/key_handle.rs, src/provider/android/provider.rs, src/provider/software/key_handle.rs, src/provider/software/provider.rs, src/storage/storage_backend/file_store.rs
=> fix(software): fix bug when deriving key ids

ts-types/package-lock.json, ts-types/package.json
* 	Override vulnerable dependency.
(ts-types depends on `typia`, which depends on `inquirer`, which depends on `external-editor`, which depends on the vulnerable `tmp:0.0.33`.)
=> Fix(ts-types): vulnerable dependency
